// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSmx7VUi9v_TiHQ4QJs_QdcvxMsh9FCj0',
    appId: '1:1086218412039:web:23326f3985ac25d4efcaa2',
    messagingSenderId: '1086218412039',
    projectId: 'daybrec-78f2c',
    authDomain: 'daybrec-78f2c.firebaseapp.com',
    storageBucket: 'daybrec-78f2c.appspot.com',
    measurementId: 'G-MFDVXWSHPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq1kcPJpXkh48q7ZTE4jLSxnIQ40lrlzo',
    appId: '1:1086218412039:android:6cecfe0ae0fcc109efcaa2',
    messagingSenderId: '1086218412039',
    projectId: 'daybrec-78f2c',
    storageBucket: 'daybrec-78f2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3IzCnHaJ03BQEhYNrLnblRs_RKkoaB6U',
    appId: '1:1086218412039:ios:02bb75bdd25e5e9eefcaa2',
    messagingSenderId: '1086218412039',
    projectId: 'daybrec-78f2c',
    storageBucket: 'daybrec-78f2c.appspot.com',
    iosClientId: '1086218412039-q4391g5m2r2821hd3dg2k2pnp0g2svd2.apps.googleusercontent.com',
    iosBundleId: 'com.example.daybrec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3IzCnHaJ03BQEhYNrLnblRs_RKkoaB6U',
    appId: '1:1086218412039:ios:02bb75bdd25e5e9eefcaa2',
    messagingSenderId: '1086218412039',
    projectId: 'daybrec-78f2c',
    storageBucket: 'daybrec-78f2c.appspot.com',
    iosClientId: '1086218412039-q4391g5m2r2821hd3dg2k2pnp0g2svd2.apps.googleusercontent.com',
    iosBundleId: 'com.example.daybrec',
  );
}
